### ISSUE TITLE
Move hard-coded values to configuration files where it's possible

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud-infra/delatore#35]
### Proposal:
Use 2 yaml configuration files for sources and for outputs that are distributed together with library:

### Proposed structure:

`sources.yaml`:
```yaml
- name: InfluxDB
  params:
    host: '...'
    port: 80
    username: '...'
    database: '...'
  publishes: 'INFLUX'
- name: AWX Client
  ...

```

`outputs.yaml`:
```yaml
- name: Telegram Bot
  params:
    api_url: 'https://api.telegram.org/bot'
  subscriptions:
  - 'INFLUX'
  - 'AWX_WEB_HOOK'
  - 'AWX_CLIENT_OUT'

```
